### ISSUE TITLE
libstdc + Xcode 15

### ISSUE THREAD

**Issue by bartceslarr** [Kila2/libstdc-.6.0.9.tbd#4]
Hi, does anyone deal with this in Xcode 15? I recently switched to a Mac with M2 and I have Sonoma installed and I cant't figure out how to make this works...

Seeing that this doesn't work, the first thing I tried was to install Xcode14 but it's not compatible with Sonoma, so I don't know what else I can do. 

I wouldn't like to downgrade my MacOs version to Monterey...

I copied the files like this:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libstdc++.6.0.9.dylib
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libstdc++.6.0.9.tbd
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libstdc++.6.0.9.dylib
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libstdc++.6.0.9.tbd

and I still get the error: Build input file cannot be found: '/usr/lib/libstdc++.6.0.9.dylib'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

Any idea of what can I do? Thanks in advance!

**Comment by Kila2** [comment]
migrate your project use libc++ instead of libstdc++

**Comment by bartceslarr** [comment]
Thanks a lot I think that solved my problem, but I had to delete some references to that old lib in some of the pods I use in my project, but now it seems that its working, thanks a lot! :)
